### ISSUE TITLE
maptalks/gl-layers安装最新版后启动报错  

### ISSUE THREAD

**Issue by whh-meteor** [maptalks/issues#719]
gltf-loader.es.js:9 Uncaught ReferenceError: e is not defined
    at eval (gltf-loader.es.js:9:865)
    at ./node_modules/@maptalks/gltf-loader/dist/gltf-loader.es.js (app.js:830:1)
    at __webpack_require__ (app.js:679:30)
    at fn (app.js:89:20)
    at eval (reshadergl.es.js:55:80)
    at ./node_modules/@maptalks/reshader.gl/dist/reshadergl.es.js (app.js:853:1)
    at __webpack_require__ (app.js:679:30)
    at fn (app.js:89:20)
    at Object.eval (maptalksgl.es.js:23:80)
    at eval (maptalksgl.es.js:6205:30)

**Comment by fuzhenn** [comment]
请改为安装 maptalks-gl
具体请参考 https://github.com/maptalks/maptalks-gl-layers
